spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123
    # 新的数据库驱动程序
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: cn.pja.api.user.model.dto
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

dubbo:
  application:
    name: pja-game-api
  registry:
    address: zookeeper://192.168.99.100:2181
    # 这个值要设置大一点 如1分钟
    timeout: 60000
  protocol:
    port: 20880
    name: dubbo
  config-center:
    timeout: 10000
  scan:
    base-packages: cn.pja.api.service