server:
  port: 7000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123
    # 新的数据库驱动程序
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # redis数据库索引（默认0）
    database: 0
    # redis服务器地址
    host: 127.0.0.1
    # redis服务器端口号
    port: 6379
    # redis服务器密码(默认为空)
    password:
    lettuce:
      pool:
        # 最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间
        max-wait: -1
        # 连接池的最大空闲连接
        max-idle: 10
        # 连接池的最小空闲连接
        min-idle: 0
      # 在关闭客户端连接之前等待任务处理完成的最长时间，在这之后，无论任务是否执行完成，都会被执行器关闭，默认100ms
      shutdown-timeout: 6000
    # 连接超时时间
    timeout: 6000

    # web页面配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false

mybatis:
  jdbc:
    jar: C:\Users\彭金安\.m2\repository\mysql\mysql-connector-java\8.0.11\mysql-connector-java-8.0.11.jar
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: cn.pja.starter.model.vo
  configuration:
    # 开启驼峰命名
    map-underscore-to-camel-case: true

dubbo:
  application:
    name: pja-game-starter
  registry:
    address: zookeeper://192.168.99.100:2181
    # 这个值要设置大一点 如1分钟
    timeout: 60000
    check: false
    register: false
  protocol:
    port: 20881
    name: dubbo
  config-center:
    timeout: 10000
  consumer:
    check: false

